### ISSUE TITLE
compress everything

### ISSUE THREAD

**Issue by corysimmons** [samccone/css-diff#1]
comments can, and probably should, vary between languages. if css-diff compresses them, it should still be able to parse tree but comments will be ignored.

this could be an option.
- http://learnboost.github.io/stylus/docs/middleware.html
- https://github.com/sass/node-sass#outputstyle

**Comment by samccone** [comment]
I think a more robust solution would be to allow the user to exclude node types during the diff

**Comment by corysimmons** [comment]
hell man, if you can do that then that would be awesome.

**Comment by corysimmons** [comment]
was just thinking compression would be the fastest solution. like a bandage

**Comment by corysimmons** [comment]
Still think this might be a valid option for situations like this: https://github.com/mojotech/jeet/pull/326
